#!/usr/bin/env perl
$version = `cat VERSION`;
chomp $version;
system( "( make clean; ".
        "  cp README ../README.ace; ".
        "  cd ..; rm -f ace-$version.zoo; ".
        "  find ace -type f | ".
        "  egrep -v 'CVS|sedf|3000|acedoc|doc3001|bin|zoo|[.]cvs".
                    "|[._]tst|[.]bbl|[.]aux|[.]toc|[.][ib]lg|[.]log".
                    "|[.]ind|[.]idx|[.]lab|[.]swp|[.]bak|~' |".
        "  zoo ahI ace-$version.zoo )" );
