name: ACE
version: "5.7.0"
license: "MIT"
date: 2025-04-10
description: |
    Advanced Coset Enumerator

authors:
    - name: Greg Gamble
      url: http://staffhome.ecm.uwa.edu.au/~00021149
    - name: Alexander Hulpke
      url: https://www.math.colostate.edu/~hulpke
    - name: George Havas
      url: http://staff.itee.uq.edu.au/havas
    - name: Colin Ramsay
      url: mailto:cram@itee.uq.edu.au

maintainers:
    - name: Greg Gamble
      url: http://staffhome.ecm.uwa.edu.au/~00021149
    - name: Max Horn
      url: https://www.quendi.de/math

GAP: ">= 4.7"

www: https://gap-packages.github.io/ace
readme: README.md
packageinfo: https://gap-packages.github.io/ace/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/ace/releases/download/v5.7.0/ace-5.7.0.tar.gz

abstract: |
    The <span class="pkgname">ACE</span> package provides both an    interactive and non-interactive interface with the Todd-Coxeter coset   enumeration functions of the ACE (Advanced Coset Enumerator) C program.

status: accepted
doc-html: htm/chapters.htm
doc-pdf: doc/manual.pdf
keywords: |
    coset enumeration, Felsch strategy, HLT strategy, coset table, index, maxcosets, activecosets.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>GHHRH25</span>]   <b class='BibAuthor'>Gamble, G., Hulpke, A., Havas, G., Ramsay, C. and Horn, M.</b>,
     <i class='BibTitle'>ACE, Advanced Coset Enumerator,
             Version 5.7.0</i>
     (<span class='BibYear'>2025</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/ace">https://gap-packages.github.io/ace</a></span>.
    </p>
    

bibtex: |
    @misc{ ACE,
      author =           {Gamble, G. and Hulpke, A. and Havas, G. and Ramsay, C.
                          and Horn, M.},
      title =            {{ACE}, {Advanced Coset Enumerator}, {V}ersion 5.7.0},
      month =            {Apr},
      year =             {2025},
      note =             {GAP package},
      howpublished =     {\href             {https://gap-packages.github.io/ace}
                          {\texttt{https://gap\texttt{\symbol{45}}packages.github.io/}\discretionary
                          {}{}{}\texttt{ace}}},
      keywords =         {coset  enumeration;  Felsch  strategy;  HLT  strategy;
                          coset table; index; maxcosets; activecosets},
      printedkey =       {GHHRH25}
    }

