# ACE, chapter 8
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("ace06.tst");

# doc/examples.xml:12-15
gap> LoadPackage("ace");
true

# doc/examples.xml:265-274
gap> ACEStats(1);
rec( activecosets := 60, cputime := 0, cputimeUnits := "10^-2 seconds", 
  index := 60, maxcosets := 66, totcosets := 76 )
gap> # Actually, we didn't need to pass an argument to ACEStats()
gap> # ... we could have relied on the default:
gap> ACEStats();
rec( activecosets := 60, cputime := 0, cputimeUnits := "10^-2 seconds", 
  index := 60, maxcosets := 66, totcosets := 76 )

# doc/examples.xml:278-364
gap> ACECosetTable(); # Interactive version of ACECosetTableFromGensAndRels()
#I  CO: a=60 r=61 h=1 n=61; c=+0.00
#I   coset |      b      B      a
#I  -------+---------------------
#I       1 |      4      3      2
#I       2 |     11     12      1
#I       3 |      1      4      5
#I       4 |      3      1     18
#I       5 |     24      6      3
#I       6 |      5     24      7
#I       7 |     30      8      6
#I       8 |      7     30      9
#I       9 |     36     10      8
#I      10 |      9     36     11
#I      11 |     12      2     10
#I      12 |      2     11     13
#I      13 |     40     14     12
#I      14 |     13     40     15
#I      15 |     46     16     14
#I      16 |     15     46     17
#I      17 |     19     18     16
#I      18 |     17     19      4
#I      19 |     18     17     20
#I      20 |     50     21     19
#I      21 |     20     50     22
#I      22 |     25     23     21
#I      23 |     22     25     24
#I      24 |      6      5     23
#I      25 |     23     22     26
#I      26 |     54     27     25
#I      27 |     26     54     28
#I      28 |     31     29     27
#I      29 |     28     31     30
#I      30 |      8      7     29
#I      31 |     29     28     32
#I      32 |     58     33     31
#I      33 |     32     58     34
#I      34 |     37     35     33
#I      35 |     34     37     36
#I      36 |     10      9     35
#I      37 |     35     34     38
#I      38 |     41     39     37
#I      39 |     38     41     40
#I      40 |     14     13     39
#I      41 |     39     38     42
#I      42 |     60     43     41
#I      43 |     42     60     44
#I      44 |     47     45     43
#I      45 |     44     47     46
#I      46 |     16     15     45
#I      47 |     45     44     48
#I      48 |     51     49     47
#I      49 |     48     51     50
#I      50 |     21     20     49
#I      51 |     49     48     52
#I      52 |     55     53     51
#I      53 |     52     55     54
#I      54 |     27     26     53
#I      55 |     53     52     56
#I      56 |     59     57     55
#I      57 |     56     59     58
#I      58 |     33     32     57
#I      59 |     57     56     60
#I      60 |     43     42     59
[ [ 2, 1, 7, 8, 9, 10, 3, 4, 5, 6, 19, 20, 21, 22, 23, 24, 25, 26, 11, 12, 
      13, 14, 15, 16, 17, 18, 37, 38, 30, 29, 39, 40, 41, 35, 34, 42, 27, 28, 
      31, 32, 33, 36, 54, 45, 44, 55, 56, 49, 48, 51, 50, 57, 58, 43, 46, 47, 
      52, 53, 60, 59 ], 
  [ 2, 1, 7, 8, 9, 10, 3, 4, 5, 6, 19, 20, 21, 22, 23, 24, 25, 26, 11, 12, 
      13, 14, 15, 16, 17, 18, 37, 38, 30, 29, 39, 40, 41, 35, 34, 42, 27, 28, 
      31, 32, 33, 36, 54, 45, 44, 55, 56, 49, 48, 51, 50, 57, 58, 43, 46, 47, 
      52, 53, 60, 59 ], 
  [ 3, 5, 4, 1, 6, 2, 11, 13, 15, 17, 12, 7, 14, 8, 16, 9, 18, 10, 26, 28, 
      30, 32, 22, 33, 35, 27, 19, 29, 20, 31, 21, 23, 34, 24, 36, 25, 43, 45, 
      47, 49, 51, 53, 44, 37, 46, 38, 48, 39, 50, 40, 52, 41, 54, 42, 59, 55, 
      60, 57, 56, 58 ], 
  [ 4, 6, 1, 3, 2, 5, 12, 14, 16, 18, 7, 11, 8, 13, 9, 15, 10, 17, 27, 29, 
      31, 23, 32, 34, 36, 19, 26, 20, 28, 21, 30, 22, 24, 33, 25, 35, 44, 46, 
      48, 50, 52, 54, 37, 43, 38, 45, 39, 47, 40, 49, 41, 51, 42, 53, 56, 59, 
      58, 60, 55, 57 ] ]
gap> # To terminate the interactive process we do:
gap> ACEQuit(1); # Again, we could have omitted the 1
gap> # If we had more than one interactive process we could have
gap> # terminated them all in one go with:
gap> ACEQuitAll();

# doc/examples.xml:371-422
gap> ACEExample();
#I                   ACEExample Index (Table of Contents)
#I                   ------------------------------------
#I  This table of possible examples is displayed when calling ACEExample 
#I  with no arguments, or with the argument: "index" (meant in the sense
#I  of `list'), or with a non-existent example name.
#I  
#I  The following ACE examples are available (in each case, for a subgroup
#I  H of a group G, the cosets of H in G are enumerated):
#I  
#I    Example          G                      H              strategy
#I    -------          -                      -              --------
#I    "A5"             A_5                    Id             default
#I    "A5-C5"          A_5                    C_5            default
#I    "C5-fel0"        C_5                    Id             felsch := 0
#I    "F27-purec"      F(2,7) = C_29          Id             purec
#I    "F27-fel0"       F(2,7) = C_29          Id             felsch := 0
#I    "F27-fel1"       F(2,7) = C_29          Id             felsch := 1
#I    "M12-hlt"        M_12 (Matthieu group)  Id             hlt
#I    "M12-fel1"       M_12 (Matthieu group)  Id             felsch := 1
#I    "SL219-hard"     SL(2,19)               |G : H| = 180  hard
#I    "perf602p5"      PerfectGroup(60*2^5,2) |G : H| = 480  default
#I  * "2p17-fel1"      |G| = 2^17             Id             felsch := 1
#I    "2p17-fel1a"     |G| = 2^17             |G : H| = 1    felsch := 1
#I    "2p17-2p3-fel1"  |G| = 2^17             |G : H| = 2^3  felsch := 1
#I    "2p17-2p14-fel1" |G| = 2^17             |G : H| = 2^14 felsch := 1
#I    "2p17-id-fel1"   |G| = 2^17             Id             felsch := 1
#I  * "2p18-fel1"      |G| = 2^18             |G : H| = 2    felsch := 1
#I  * "big-fel1"       |G| = 2^18.3           |G : H| = 6    felsch := 1
#I  * "big-hard"       |G| = 2^18.3           |G : H| = 6    hard
#I  
#I  Notes
#I  -----
#I  1. The example (first) argument of ACEExample() is a string; each
#I     example above is in double quotes to remind you to include them.
#I  2. By default, ACEExample applies ACEStats to the chosen example. You 
#I     may alter the ACE function used, by calling ACEExample with a 2nd 
#I     argument; choose from: ACECosetTableFromGensAndRels (or, equival-
#I     ently ACECosetTable), or ACEStart, e.g. `ACEExample("A5", ACEStart);'
#I  3. You may call ACEExample with additional ACE options (entered after a
#I     colon in the usual way for options), e.g. `ACEExample("A5" : hlt);' 
#I  4. Try the *-ed examples to explore how to modify options when an
#I     enumeration fails (just follow the instructions you get within the
#I     break-loop, or see Notes 2. and 3.).
#I  5. Try `SetInfoLevel(InfoACE, 3);' before calling ACEExample, to see the
#I     effect of setting the "mess" (= "messages") option.
#I  6. To suppress a long output, use a double semicolon (`;;') after the
#I     ACEExample command. (However, this does not suppress Info-ed output.)
#I  7. Also, try `SetInfoLevel(InfoACE, 2);' or `SetInfoLevel(InfoACE, 4);'
#I     before calling ACEExample.

# doc/examples.xml:543-586
gap> SetInfoLevel(InfoACE, 2);
gap> ACEExample("F27-purec", ACECosetTableFromGensAndRels
>               : sg := ["c"], subgroup := "< c >", messages := 0);
#I  # ACEExample "F27-purec" : enumeration of cosets of H in G,
#I  # where G = F(2,7) = C_29, H = Id, using purec strategy.
#I  #
#I  # F, G, a, b, c, d, e, x, y are local to ACEExample
#I  # We define F(2,7) on 7 generators
#I  F := FreeGroup("a","b","c","d","e", "x", "y"); 
#I       a := F.1;  b := F.2;  c := F.3;  d := F.4; 
#I       e := F.5;  x := F.6;  y := F.7;
#I  G := F / [a*b*c^-1, b*c*d^-1, c*d*e^-1, d*e*x^-1, 
#I            e*x*y^-1, x*y*a^-1, y*a*b^-1];
#I  ACECosetTableFromGensAndRels(
#I      FreeGeneratorsOfFpGroup(G), 
#I      RelatorsOfFpGroup(G), 
#I      [] # Generators of identity subgroup (empty list)
#I      # Options that don't affect the enumeration
#I      : echo, enum := "F(2,7), aka C_29", subg := "Id", 
#I      # Other options
#I      wo := "2M", mess := 25000, purec, 
#I      # User Options
#I        subgroup := "< c >",
#I        sg := [ "c" ],
#I        messages := 0);
ACECosetTableFromGensAndRels called with the following arguments:
 Group generators : [ a, b, c, d, e, x, y ]
 Group relators : [ a*b*c^-1, b*c*d^-1, c*d*e^-1, d*e*x^-1, e*x*y^-1, 
  x*y*a^-1, y*a*b^-1 ]
 Subgroup generators : [  ]
ACECosetTableFromGensAndRels called with the following options:
 subgroup := < c >
 enum := F(2,7), aka C_29
 aceexampleoptions := true (inserted by ACEExample, not passed to ACE)
 sg := [ "c" ] (brackets are not passed to ACE)
 echo := true (not passed to ACE)
 messages := 0
 purec (no value, passed to ACE via option: pure c)
 wo := 2M
#I  INDEX = 1 (a=1 r=2 h=2 n=2; l=4 c=0.00; m=332 t=332)
[ [ 1 ], [ 1 ], [ 1 ], [ 1 ], [ 1 ], [ 1 ], [ 1 ], [ 1 ], [ 1 ], [ 1 ], 
  [ 1 ], [ 1 ], [ 1 ], [ 1 ] ]

# doc/examples.xml:599-602
gap> NormalOnBreak := OnBreak;; # Save the old value to restore it later
gap> OnBreak := function() Where(0); end;;

# doc/examples.xml:754-756
gap> OnBreak := NormalOnBreak;;

# doc/examples.xml:774-795
gap> ACEReadResearchExample();
#I  The following are now defined:
#I  
#I  Functions:
#I    PGRelFind, ClassesGenPairs, TranslatePresentation,
#I    IsACEResExampleOK
#I  Variables:
#I    ACEResExample, ALLRELS, newrels, F, a, b, newF, x, y,
#I    L2_8, L2_16, L3_3s, U3_3s, M11, M12, L2_32,
#I    U3_4s, J1s, L3_5s, PSp4_4s, presentations
#I  
#I  Also:
#I  
#I  TCENUM = ACETCENUM  (Todd-Coxeter Enumerator is now ACE)
#I  
#I  For an example of their application, you might like to try:
#I  gap> ACEReadResearchExample("doL28.g" : optex := [1,2,4,5,8]);
#I  (the output is 65 lines followed by a 'gap> ' prompt)
#I  
#I  For information type: ?Using ACEReadResearchExample

#
gap> STOP_TEST("ace06.tst", 1);
