# ACE, chapter 4
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("ace03.tst");

# doc/options.xml:342-345
gap> KnownACEOptions.compaction;
[ 3, [ 0 .. 100 ] ]

# doc/options.xml:348-351
gap> KnownACEOptions.ct;
[ 2, <Category "IsInt"> ]

# doc/options.xml:443-446
gap> ACEStrategyOptions;
[ "default", "easy", "felsch", "hard", "hlt", "purec", "purer", "sims" ]

# doc/options.xml:466-469
gap> Concatenation( [ "messages" ], ACEOptionSynonyms.("messages") );
[ "messages", "monitor" ]

# doc/options.xml:1219-1221
gap> SetInfoLevel(InfoACE, 3);

#
gap> STOP_TEST("ace03.tst", 1);
