# ACE, chapter 6
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("ace04.tst");

# doc/interact.xml:1547-1558
gap> ACEContinue( i : max := 100 );;
Error, Variable: 'i' must have a value
gap> IsCompleteACECosetTable( i );
Error, Variable: 'i' must have a value
gap> ACEConjugatesForSubgroupNormalClosure( i : add );
Error, Variable: 'i' must have a value
gap> IsCompleteACECosetTable( i );
Error, Variable: 'i' must have a value
gap> ACEStats( i ).index;
Error, Variable: 'i' must have a value

# doc/interact.xml:1564-1569
gap> ACEConjugatesForSubgroupNormalClosure( i : add );
Error, Variable: 'i' must have a value
gap> ACEStats( i ).index;
Error, Variable: 'i' must have a value

# doc/interact.xml:1574-1579
gap> ACEConjugatesForSubgroupNormalClosure( i : add );
Error, Variable: 'i' must have a value
gap> ACESubgroupGenerators( i );
Error, Variable: 'i' must have a value

#
gap> STOP_TEST("ace04.tst", 1);
