# ACE, chapter 9
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("ace07.tst");

# doc/moreexamples.xml:40-42
gap> F := FreeGroup("a", "b");; fgens := FreeGeneratorsOfFpGroup(F);;

# doc/moreexamples.xml:51-53
gap> SetInfoLevel(InfoACE, 2);

# doc/moreexamples.xml:372-376
gap> ACEStats(1); # The interactive version of ACEStats takes 1 or no arg'ts
Error, no such interactive ACE session


# doc/moreexamples.xml:383-387
gap> ACEDisplayCosetTable(1, [-1, 12]);
Error, no such interactive ACE session


# doc/moreexamples.xml:398-402
gap> ACEStart(1 : max := 12);
Error, no such interactive ACE session


# doc/moreexamples.xml:405-409
gap> ACEDisplayCosetTable(1, [-1, 12]);
Error, no such interactive ACE session


# doc/moreexamples.xml:413-417
gap> ACECosetTable(1 : incomplete);
Error, no such interactive ACE session


# doc/moreexamples.xml:451-464
gap> SetInfoLevel(InfoACE, 4);
gap> a := F.1;; b := F.2;;
gap> # Enumerating A_5 = < a, b || a^2, b^3, (a*b)^5 >
gap> # over Id (trivial subgp)
gap> ACEStart(1, fgens, [a^2, b^3, (a*b)^5], []
>                                     # 4th arg empty (to define Id)
>             : enumeration := "A_5", # Define the Group Name
>               subgroup := "Id",     # Define the Subgroup Name
>               max := 0,             # Set `max' back to default (no limit)
>               messages := 1000);    # Progress messages every 1000 iter'ns
Error, no such interactive ACE session


# doc/moreexamples.xml:478-486
gap> ACEStart(1 : relators := ToACEWords(fgens, [a^2, b^3, (a*b)^5]),
>                 enumeration := "A_5",
>                 subgroup := "Id",
>                 max := 0,
>                 messages := 1000);
Error, no such interactive ACE session


# doc/moreexamples.xml:505-509
gap> ACEGroupGenerators(1) = fgens;
Error, no such interactive ACE session


# doc/moreexamples.xml:511-516
gap> fgens := ACEGroupGenerators(1);;
Error, no such interactive ACE session

gap> F := GroupWithGenerators(fgens);; a := F.1;; b := F.2;;

# doc/moreexamples.xml:527-533
gap> SetInfoLevel(InfoACE, 3);
gap> ACEStart(1, ACEGroupGenerators(1), ACERelators(1), [ a*b ]
>             : messages := 1);
Error, no such interactive ACE session


# doc/moreexamples.xml:550-554
gap> ACEDumpStatistics();
#I  No interactive ACE sessions are currently active
Error, no currently active interactive ACE sessions

# doc/moreexamples.xml:566-570
gap> ACEDisplayCosetTable([-12]);
#I  No interactive ACE sessions are currently active
Error, no currently active interactive ACE sessions

# doc/moreexamples.xml:587-594
gap> ACEStandardCosetNumbering();
#I  No interactive ACE sessions are currently active
Error, no currently active interactive ACE sessions
gap> ACEDisplayCosetTable([-12]);
#I  No interactive ACE sessions are currently active
Error, no currently active interactive ACE sessions

# doc/moreexamples.xml:607-620
gap> SetInfoLevel(InfoACE, 4);
gap> ACEStart(1, ACEGroupGenerators(1), ACERelators(1), [ a*b ]
>             : messages := 0, lenlex);
Error, no such interactive ACE session

gap> ACEStandardCosetNumbering();
#I  No interactive ACE sessions are currently active
Error, no currently active interactive ACE sessions
gap> # The capitalised `CO' indicates space was recovered during compaction
gap> ACEDisplayCosetTable([-12]);
#I  No interactive ACE sessions are currently active
Error, no currently active interactive ACE sessions

# doc/moreexamples.xml:690-700
gap> ACEEvenSims := function(fgens, rels, sgens, i, maxstart, maxstep)
>      local j;
>      j := ACEStart(fgens, rels, sgens : sims := i, max := maxstart);
>      while ACEStats(j).index = 0 do
>        ACEStandardCosetNumbering(j);
>        ACEContinue(j : max := ACEParameters(j).max + maxstep);
>      od;
>      return ACEStats(j);
>    end;;

#
gap> STOP_TEST("ace07.tst", 1);
