# ACE, chapter 4
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("ace03.tst");

# doc/options.xml:16-31
gap> RecNames(KnownACEOptions);
[ "default", "help", "check", "generators", "start", "cycles", "normal", 
  "ds", "group", "subgroup", "relators", "order", "max", "rep", "system", 
  "silent", "ct", "easy", "time", "begin", "text", "options", "fill", 
  "aceinfile", "aceignore", "aceignoreunknown", "acenowarnings", "aceecho", 
  "aceincomment", "aceexampleoptions", "lenlex", "semilenlex", "incomplete", 
  "sg", "rl", "aep", "ai", "ao", "aceoutfile", "asis", "bye", "exit", "qui", 
  "cc", "cfactor", "redo", "compaction", "continu", "dmode", "dsize", "dr", 
  "dump", "echo", "enumeration", "felsch", "ffactor", "hard", "hlt", "hole", 
  "lookahead", "loop", "mendelsohn", "messages", "monitor", "mode", "nc", 
  "no", "oo", "path", "pmode", "psize", "sr", "print", "purec", "purer", 
  "rc", "recover", "contiguous", "rfactor", "rt", "row", "sc", "stabilising", 
  "sims", "standard", "statistics", "stats", "style", "tw", "trace", 
  "workspace" ]

# doc/options.xml:342-345
gap> KnownACEOptions.compaction;
[ 3, [ 0 .. 100 ] ]

# doc/options.xml:348-351
gap> KnownACEOptions.ct;
[ 2, <Category "IsInt"> ]

# doc/options.xml:443-446
gap> ACEStrategyOptions;
[ "default", "easy", "felsch", "hard", "hlt", "purec", "purer", "sims" ]

# doc/options.xml:466-469
gap> Concatenation( [ "messages" ], ACEOptionSynonyms.("messages") );
[ "messages", "monitor" ]

# doc/options.xml:738-745
gap> Concatenation( List(RecNames(ACEParameterOptions),
>                        optname -> ACEOptionData(optname).synonyms) );
[ "subgroup", "max", "ct", "cfactor", "time", "fill", "ffactor", "asis", 
  "compaction", "dmode", "dsize", "enumeration", "hole", "lookahead", "loop", 
  "mendelsohn", "messages", "monitor", "no", "path", "pmode", "psize", "rt", 
  "rfactor", "row", "workspace" ]

# doc/options.xml:1219-1221
gap> SetInfoLevel(InfoACE, 3);

#
gap> STOP_TEST("ace03.tst", 1);
