# ACE, chapter 9
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("ace06.tst");

# doc/moreexamples.xml:40-42
gap> F := FreeGroup("a", "b");; fgens := FreeGeneratorsOfFpGroup(F);;

# doc/moreexamples.xml:51-53
gap> SetInfoLevel(InfoACE, 2);

# doc/moreexamples.xml:888-898
gap> ACEEvenSims := function(fgens, rels, sgens, i, maxstart, maxstep)
>      local j;
>      j := ACEStart(fgens, rels, sgens : sims := i, max := maxstart);
>      while ACEStats(j).index = 0 do
>        ACEStandardCosetNumbering(j);
>        ACEContinue(j : max := ACEParameters(j).max + maxstep);
>      od;
>      return ACEStats(j);
>    end;;

#
gap> STOP_TEST("ace06.tst", 1);
