
/*******************************************************************************

  ex1a.c
  19 Jan 99, 30 Apr 14
  Colin Ramsay, uqcramsa@uq.edu.au

Copyright (c)  2014  Centre for Discrete Mathematics and Computing, 
                     The University of Queensland, Australia

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.


This is a simple example of how to drive ACE Level 1 (ie, the core plus the demo
wrapper) directly.  No attempt is made to be terribly clever, or general 
purpose, or to do much error checking.  As our example, we use F(2,7), which has
order 29, and is generated by any of its generators (we  use 'e').  We use 
R*-style.  This works quite nicely, with a 'good' set of parameters being:
 
  Group Name: F(2,7);
  Group Generators: a,b,c,d,e,f,g;
  Group Relators: ab=c, bc=d, cd=e, de=f, ef=g, fg=a, ga=b;
  Subgroup Name: trivial;
  Subgroup Generators: ;
  Wo:1000000; Max:71426; Mess:5000; Ti:-1; Ho:-1; Loop:0
  As:0; Path:0; Row:1; Mend:0; No:7; Look:1; Com:10;
  C:0; R:-1000; Fi:20; PMod:0; PSiz:256; DMod:3; DSiz:250;

notes:
- The screen needs to be at least 124 chars wide to accommodate the output.

*******************************************************************************/

#include "al1.h"

#include <string.h>
#include <time.h>

/*******************************************************************************
Stuff from level 2 ...
*******************************************************************************/

SInt mode;                         /* cf. the "mode" argument to al1_start() */

static char *datetime(void)
  {
  time_t t = time(NULL);
  return ctime(&t);
  }

/*******************************************************************************
Build the presentation and the (empty) subgroup ...
*******************************************************************************/

#define R   rellst
#define RL  rellst->last
#define RLW rellst->last->word

void bld_pres(void)
  {
  int i;

  grpname = (char *)malloc(6+1);
  strcpy(grpname, "F(2,7)");

  ndgen = 7;
  galpha = TRUE;

  for (i = 0; i < 27; i++) { algen[i] = '\0'; }
  algen[1] = 'a';			    /* Generator 1 is 'a' ... */
  algen[2] = 'b';
  algen[3] = 'c';
  algen[4] = 'd';
  algen[5] = 'e';
  algen[6] = 'f';
  algen[7] = 'g';

  for (i = 0; i < 27; i++) { genal[i] = 0; }
  genal[1] = 1;
  genal[2] = 2;
  genal[3] = 3;
  genal[4] = 4;
  genal[5] = 5;
  genal[6] = 6;
  genal[7] = 7;

  R = al1_newwl();

  R->first = RL = al1_newelt();
  R->len++;
  RLW = (SInt*)malloc((3+1)*sizeof(SInt));
  RLW[0] = 0;				    /* Not used */
  RLW[1] = 1;				    /* 'a' */
  RLW[2] = 2;				    /* 'b' */
  RLW[3] = -3;				    /* 'C' = 'c^-1' */
  RL->len = 3;
  RL->exp = 1;
  RL->next = NULL;

  RL = (RL->next = al1_newelt());
  R->len++;
  RLW = (SInt*)malloc((3+1)*sizeof(SInt));
  RLW[0] = 0;
  RLW[1] = 2;
  RLW[2] = 3;
  RLW[3] = -4;
  RL->len = 3;
  RL->exp = 1;
  RL->next = NULL;

  RL = (RL->next = al1_newelt());
  R->len++;
  RLW = (SInt*)malloc((3+1)*sizeof(SInt));
  RLW[0] = 0;
  RLW[1] = 3;
  RLW[2] = 4;
  RLW[3] = -5;
  RL->len = 3;
  RL->exp = 1;
  RL->next = NULL;

  RL = (RL->next = al1_newelt());
  R->len++;
  RLW = (SInt*)malloc((3+1)*sizeof(SInt));
  RLW[0] = 0;
  RLW[1] = 4;
  RLW[2] = 5;
  RLW[3] = -6;
  RL->len = 3;
  RL->exp = 1;
  RL->next = NULL;

  RL = (RL->next = al1_newelt());
  R->len++;
  RLW = (SInt*)malloc((3+1)*sizeof(SInt));
  RLW[0] = 0;
  RLW[1] = 5;
  RLW[2] = 6;
  RLW[3] = -7;
  RL->len = 3;
  RL->exp = 1;
  RL->next = NULL;

  RL = (RL->next = al1_newelt());
  R->len++;
  RLW = (SInt*)malloc((3+1)*sizeof(SInt));
  RLW[0] = 0;
  RLW[1] = 6;
  RLW[2] = 7;
  RLW[3] = -1;
  RL->len = 3;
  RL->exp = 1;
  RL->next = NULL;

  RL = (RL->next = al1_newelt());
  R->len++;
  RLW = (SInt*)malloc((3+1)*sizeof(SInt));
  RLW[0] = 0;
  RLW[1] = 7;
  RLW[2] = 1;
  RLW[3] = -2;
  RL->len = 3;
  RL->exp = 1;
  RL->next = NULL;

  subgrpname = (char *)malloc(7+1);
  strcpy(subgrpname, "trivial");

  genlst = NULL;
  }

/*******************************************************************************
Change subgroup to <e> ...
*******************************************************************************/

void edit_pres(void)
  {
  strcpy(subgrpname, "self");

  genlst = al1_newwl();

  genlst->first = genlst->last = al1_newelt();
  genlst->len++;
  genlst->last->word = (SInt*)malloc((1+1)*sizeof(SInt));
  genlst->last->word[0] = 0;			 /* Not used */
  genlst->last->word[1] = 5;			 /* 'e' */
  genlst->last->len = 1;
  genlst->last->exp = 1;
  genlst->last->next = NULL;
  }

int main(void)
  {
  int b;
  Coset i;
  SInt j;

  printf("\n");
  printf("%s (Level 1): example programme \"a\"\n", ACEVER);
  printf("Start time: %s", datetime());
  for (b = 0; b < 5; b++) { printf("---------------"); }
  printf("\n");

  /* Set all parameters to defaults, and then 'tweak' some of them. */

  al1_init();

  rfactor1 = -1000;
  cfactor1 = 0;

  dedmode = 3;
  dedsiz1 = 250;

  /* If you want to play with the parameters, put stuff here. */

  /* mendel = TRUE; */
  /* rfill = FALSE; */
  
  /* Create the table workspace */

  costable = 
       (Entry*)malloc((size_t)workspace*(size_t)workmult*(size_t)sizeof(Entry));

  /* Enumeration #1: a "start", over the trivial subgroup ... */

  bld_pres();

  msgctrl = TRUE;
  msgincr = 5000;

  printf("\n");
  printf("** Start, over <1> ...\n");
  printf("\n");

  mode = 0;
  al1_rslt(al1_start(mode));

  printf("\n");
  printf("First part of full table (incl. all non-redundant cosets) ...\n");
  printf("\n");

  al1_prtct(1,42,TRUE,TRUE);

  printf("\n");
  printf("The non-redundant cosets ...\n");
  printf("\n");

  al1_prtct(1,nextdf-1,FALSE,FALSE);

  printf("\n");
  printf("Full table, after compaction ...\n");
  printf("\n");

  al0_compact();
  al1_prtct(1,nextdf-1,TRUE,TRUE);

  printf("\n");
  printf("Full table, after standardisation ...\n");
  printf("\n");

  al0_stdct();
  al1_prtct(1,nextdf-1,TRUE,TRUE);

  /* Enumeration #2: a "redo", over the subgroup <e> ... */

  edit_pres();

  msgincr = 1;

  printf("\n");
  printf("** Redo, over <e> ...\n");
  printf("\n");

  mode = 2;
  al1_rslt(al1_start(mode));

  /* Print the `full' table.  We need to do this explicitly, since al1_prtct()
  won't let us print past nextdf-1, and we want to see the coincs from the 
  collapse. */

  printf("\n");
  printf("Collapsed coset table, with coincidence queue ...\n");

  printf("\n");
  printf("     |");
  for (j = 0; j < 7; j++) { printf("   %c   %c", (int)('a'+j), (int)('A'+j)); }
  printf("\n");
  printf(" ----+");
  for (j = 0; j < 7; j++) { printf("--------"); }
  printf("\n");
  for (i = 1; i <= 29; i++)
    {
    printf("%4"PC" |", i);
    for (j = 1; j <= ncol; j++) { printf("%4"PC, (Coset)CT(i,j)); }
    printf("\n");
    }

  printf ("\n");
  for (b = 0; b < 5; b++) { printf("---------------"); }
  printf("\n");
  printf("Stop time: %s", datetime());
  printf ("\n");

  exit(EXIT_SUCCESS);
  }

