name: CI

# Trigger the workflow on push or pull request
on:
  push:
    branches:
      - master
  pull_request:

# the `concurrency` settings ensure that not too many CI jobs run in parallel
concurrency:
  # group by workflow and ref; the last slightly strange component ensures that for pull
  # requests, we limit to 1 concurrent job, but for the master branch we don't
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.ref != 'refs/heads/master' || github.run_number }}
  # Cancel intermediate builds, but only if it is a pull request build.
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  # The CI test job
  test:
    name: GAP ${{ matrix.gap-version }} ${{ matrix.ABI == '32' && '(' || '' }}${{ matrix.ABI }}${{ matrix.ABI == '32' && '-bit)' || '' }}
    runs-on: ubuntu-latest
    env:
      ABI: ${{ matrix.ABI }}
    strategy:
      fail-fast: false
      matrix:
        gap-version:
          - master
          - stable-4.15
          - '4.14'
          - '4.13'
          - '4.12'
          - '4.11'
          - '4.10'
          - stable-4.9
        ABI:
          - ''
        include:
          - gap-version: master
            ABI: '32'

    steps:
      - uses: actions/checkout@v5
      - name: "Install 32-bit Ubuntu packages"
        if: ${{ runner.os == 'Linux' && matrix.ABI == '32' }}
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          packages=(
            libgmp-dev:i386
            libreadline-dev:i386
            zlib1g-dev:i386
            gcc-multilib
            g++-multilib
          )
          sudo apt-get install "${packages[@]}"
      - uses: gap-actions/setup-gap@v3
        with:
          gap-version: ${{ matrix.gap-version }}
      - uses: gap-actions/build-pkg@v2
      - uses: gap-actions/run-pkg-tests@v4
      - uses: gap-actions/run-pkg-tests@v4
        with:
          mode: 'onlyneeded'
      - uses: gap-actions/process-coverage@v3
      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  # The documentation job
  manual:
    name: Build manuals
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: gap-actions/setup-gap@v3
      - uses: gap-actions/build-pkg-docs@v2
        with:
          use-latex: true
      - name: 'Upload documentation'
        uses: actions/upload-artifact@v4
        with:
          name: manual
          path: ./doc/manual.pdf
          if-no-files-found: error
